# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5b70165b9b5e22aa64fd583715d318239b24b3c7a2512e3be24bee22b08330ce43591cf2cb2319490ee357868349da2305d8ad644d5a94adddad57dfbae7e38

test:
  secret_key_base: 049737db0ad26effaacf658153eb09f60adcc11378851a9b07a03984154d75a7e4d49447b25ad9b7fedc03b8eb0707617323e9125250170e56d0ba4c4b828739

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
